usage:
	echo "please use the following dependencies: encrypt, decrypt, hash"
encrypt:
	@python3 encryptWithMatrix.py $(ARGS)
decrypt:
	@python3 decryptWithMatrix.py $(ARGS)
bruteforce:
	@python3 bruteForceDecrypt.py $(ARGS)
hash:
	@python3 hashWithMatrix.py $(ARGS)
